baseurl = "https://github.com/badarshahzad54/badarshahzad54.github.io.git"
theme = "hugo-geo"
themesdir = "themes"
relativeURLs = false
publishDir = "docs"
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "badarshahzad54@gmail.com"

	profilepic = "img/profile.png"
	
	title = "Badar Shahzad"
	subtitle = "MY Hugo Blog"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/badarshahzad"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/badarshahzad54"
	[[params.socialbuttons]] 
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/badarshahzad/"
	[[params.socialbuttons]]
	faicon = "google-plus"
	url = "https://plus.google.com/+Badrkhan2016"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"
